[package]
name = "substrate-archive"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[workspace]
members = [
	"polkadot-archive",
]

[dependencies]
log = "0.4"
futures = "0.1"
tokio = "0.1"
failure = "0.1"
chrono = "0.4"
primitive-types = "0.5"
dotenv = "0.14"
url = "1.7"
serde = { version = "1.0.41", features = ["derive"] }
serde_json = { version = "1.0.41", features = ["arbitrary_precision"] }
r2d2 = "0.8"
tokio-threadpool = "0.1"
dirs = "2.0.2"

fern = { version = "0.5", features = ["colored"] }
diesel = { version = "1.4", features = ["postgres", "chrono", "numeric", "r2d2", "serde_json"] }
codec = { package = "parity-scale-codec", version = "1.0.0" }
jsonrpc-core-client = { branch = "master", git = "https://github.com/paritytech/jsonrpc", features = ["ws", "arbitrary_precision"] }
runtime-metadata = { git = "https://github.com/paritytech/substrate/", package = "paint-metadata", branch = "polkadot-master" }
paint-system = { git = "https://github.com/paritytech/substrate/", package = "paint-system", branch="polkadot-master"}
substrate-rpc-api = { git = "https://github.com/paritytech/substrate/", package = "substrate-rpc-api", branch="polkadot-master"}
substrate-rpc-primitives = { git = "https://github.com/paritytech/substrate", package = "substrate-rpc-primitives", branch="polkadot-master"}
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "substrate-primitives", branch="polkadot-master"}
runtime-primitives = { git = "https://github.com/paritytech/substrate/", package = "sr-primitives", branch="polkadot-master"}
runtime-support = { git = "https://github.com/paritytech/substrate/", package = "paint-support", branch="polkadot-master"}
inherents = { git = "https://github.com/paritytech/substrate/", package = "substrate-inherents", branch="polkadot-master"}


# paint-assets = { git = "https://github.com/paritytech/substrate/", package = "paint-assets", branch="polkadot-master"}
paint-nicks = {git = "https://github.com/paritytech/substrate/", package = "paint-nicks", branch = "polkadot-master"}
paint-staking = {git = "https://github.com/paritytech/substrate/", package = "paint-staking", branch = "polkadot-master"}
paint-grandpa = {git = "https://github.com/paritytech/substrate/", package = "paint-grandpa", branch = "polkadot-master"}
paint-babe = {git = "https://github.com/paritytech/substrate/", package = "paint-babe", branch = "polkadot-master"}
paint-session = { git = "https://github.com/paritytech/substrate/", package = "paint-session", branch = "polkadot-master"}
paint-aura = { git = "https://github.com/paritytech/substrate/", package = "paint-aura", branch = "polkadot-master"}
paint-timestamp = { git = "https://github.com/paritytech/substrate/", package = "paint-timestamp", branch = "polkadot-master"}
paint-finality-tracker = { git = "https://github.com/paritytech/substrate", package = "paint-finality-tracker", branch = "polkadot-master"}
paint-sudo = { git = "https://github.com/paritytech/substrate", package = "paint-sudo", branch = "polkadot-master"}
paint-im-online = { git = "https://github.com/paritytech/substrate", package = "paint-im-online", branch = "polkadot-master"}
paint-treasury = { git = "https://github.com/paritytech/substrate", package = "paint-treasury", branch = "polkadot-master"}
paint-elections-phragmen = { git = "https://github.com/paritytech/substrate", package = "paint-elections-phragmen", branch = "polkadot-master"}
paint-balances = { git = "https://github.com/paritytech/substrate", package = "paint-balances", branch = "polkadot-master"}
derive_more = "0.15.0"

[dependencies.polkadot-runtime]
git = "https://github.com/insipx/polkadot"
package = "polkadot-runtime"
default-features = false
branch = "insipx/archive-patches"
features = ["std"]

[patch.crates-io]
jsonrpc-core-client = { git = "https://github.com/paritytech/jsonrpc", branch = "master", features = ["ws", "arbitrary_precision"] }
jsonrpc-client-transports = { git = "https://github.com/paritytech/jsonrpc", branch = "master", features = ["ws", "arbitrary_precision"] }
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", branch = "master", features = ["arbitrary_precision"] }
jsonrpc-derive = { git = "https://github.com/paritytech/jsonrpc", branch = "master" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc", branch = "master" }
codec = { git = "https://github.com/insipx/parity-scale-codec", branch = "insipx/debugging", package = "parity-scale-codec" }

[dev-dependencies]
node-runtime = { git = "https://github.com/paritytech/substrate", package="node-runtime", branch="polkadot-master" }
rand = "0.7"
