[package]
name = "substrate-archive"
version = "0.1.0"
authors = ["Andrew Plaza <andrew.plaza@parity.io>"]
edition = "2018"

[lib]
path = "archive-core/lib.rs"

[workspace]
members = [
	"polkadot-archive"
]

[dependencies]
log = "0.4"
env_logger = "0.6"
futures = "0.1"
futures-retry = "0.3"
tokio = "0.1"
failure = "0.1"
substrate-subxt = { git = "https://github.com/paritytech/substrate-subxt/" }
substrate-rpc-api = { git = "https://github.com/paritytech/substrate/", package = "substrate-rpc-api" }
substrate-rpc-primitives = { git = "https://github.com/paritytech/substrate", package = "substrate-rpc-primitives" }
substrate-primitives = { git = "https://github.com/paritytech/substrate/", package = "substrate-primitives" }
runtime-primitives = { git = "https://github.com/paritytech/substrate/", package = "sr-primitives" }
jsonrpc-core-client = { version = "13.0", features = ["ws"] }
