[package]
name = "polkadot-archive"
version = "0.1.0"
authors = ["Andrew Plaza <aplaza@liquidthink.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
failure = "0.1"
codec = { version = "~1.0.0", package = "parity-scale-codec" }
env_logger = "0.7.0"
substrate-archive = { path = "../" }

[dependencies.polkadot-runtime]
git = "https://github.com/insipx/polkadot"
package = "polkadot-runtime"
default-features = false
branch = "insipx/archive-patches"
features = ["std"]
